name: CI

on:
  pull_request:
  push:
    branches:
      - 'master'
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout commit
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Fetch history
        run: git fetch --prune --unshallow --recurse-submodules=no

      - name: Checkout Head Ref
        if: github.head_ref != ''
        run: |
          git checkout -b ${{ github.head_ref }} || git checkout ${{ github.head_ref }}

      - name: Set up .NET environment
        uses: vrnobody/Setup-DotNetFrameworkEnv@v1.20

      - name: Install NuGet packages
        run: nuget restore LiveSplit\LiveSplit.sln

      - name: Build LiveSplit
        run: msbuild LiveSplit\LiveSplit.sln /verbosity:minimal /p:NoWarn=1591 /p:Configuration=Release

      - name: Run tests
        run: |
          & "vstest.console.exe" "LiveSplit/LiveSplit.Tests/bin/Release/LiveSplit.Tests.dll"

      - name: Create a folder for the Server component artifacts
        run: |
          mkdir .\LiveSplit.Server
          Move-Item -path .\LiveSplit\bin\Release\Components\LiveSplit.Server.dll -destination .\LiveSplit.Server
          Move-Item -path .\LiveSplit\bin\Release\Components\Noesis.Javascript.dll -destination .\LiveSplit.Server

      - name: Upload the Server component as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: LiveSplit.Server
          path: LiveSplit.Server

      - name: Upload the Counter component as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: LiveSplit.Counter
          path: LiveSplit/bin/Release/Components/LiveSplit.Counter.dll

      - name: Clean up build folder
        run: |
          mkdir .\LiveSplit\bin\Release\Resources
          cp .\LiveSplit\Resources\SplitsFile.ico .\LiveSplit\bin\Release\Resources\
          cp .\LiveSplit\Resources\LayoutFile.ico .\LiveSplit\bin\Release\Resources\
          cd LiveSplit\bin\Release
          Get-ChildItem * -Include *.xml -Recurse | Remove-Item
          Get-ChildItem * -Include *.pdb -Recurse | Remove-Item
          Get-ChildItem * -Include *MSTest*.dll -Recurse | Remove-Item
          Get-ChildItem * -Include *LiveSplit.Counter.dll -Recurse | Remove-Item

      - name: Upload build as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: LiveSplit_Build
          path: LiveSplit/bin/Release